<?xml version="1.0" encoding="utf-8"?><Database Name="Test" Class="EntitiesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=Test;Persist Security Info=True;User ID=sa" SettingsObjectName="DevExpressGridExample.Entities.Properties.Settings" SettingsPropertyName="TestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.STI" Member="STIs">
    <Type Name="STI">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IslemTur" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EvrakNo" Type="System.String" DbType="VarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tarih" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MalKodu" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Miktar" Type="System.Decimal" DbType="Decimal(25,6) NOT NULL" CanBeNull="false" />
      <Column Name="Fiyat" Type="System.Decimal" DbType="Decimal(25,6) NOT NULL" CanBeNull="false" />
      <Column Name="Tutar" Type="System.Decimal" DbType="Decimal(25,6) NOT NULL" CanBeNull="false" />
      <Column Name="Birim" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.STK" Member="STKs">
    <Type Name="STK">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MalKodu" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MalAdi" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>