#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExpressGridExample.Entities.Entity
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Test")]
	public partial class EntitiesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSTI(STI instance);
    partial void UpdateSTI(STI instance);
    partial void DeleteSTI(STI instance);
    partial void InsertSTK(STK instance);
    partial void UpdateSTK(STK instance);
    partial void DeleteSTK(STK instance);
    #endregion
		
		public EntitiesDataContext() : 
				base(global::DevExpressGridExample.Entities.Properties.Settings.Default.TestConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EntitiesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntitiesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntitiesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntitiesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<STI> STIs
		{
			get
			{
				return this.GetTable<STI>();
			}
		}
		
		public System.Data.Linq.Table<STK> STKs
		{
			get
			{
				return this.GetTable<STK>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_veridoldur")]
		public ISingleResult<sp_veridoldurResult> sp_veridoldur([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> baslangicTarihi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> bitisTarihi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string malKodu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), baslangicTarihi, bitisTarihi, malKodu);
			return ((ISingleResult<sp_veridoldurResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STI")]
	public partial class STI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private short _IslemTur;
		
		private string _EvrakNo;
		
		private int _Tarih;
		
		private string _MalKodu;
		
		private decimal _Miktar;
		
		private decimal _Fiyat;
		
		private decimal _Tutar;
		
		private string _Birim;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnIslemTurChanging(short value);
    partial void OnIslemTurChanged();
    partial void OnEvrakNoChanging(string value);
    partial void OnEvrakNoChanged();
    partial void OnTarihChanging(int value);
    partial void OnTarihChanged();
    partial void OnMalKoduChanging(string value);
    partial void OnMalKoduChanged();
    partial void OnMiktarChanging(decimal value);
    partial void OnMiktarChanged();
    partial void OnFiyatChanging(decimal value);
    partial void OnFiyatChanged();
    partial void OnTutarChanging(decimal value);
    partial void OnTutarChanged();
    partial void OnBirimChanging(string value);
    partial void OnBirimChanged();
    #endregion
		
		public STI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IslemTur", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short IslemTur
		{
			get
			{
				return this._IslemTur;
			}
			set
			{
				if ((this._IslemTur != value))
				{
					this.OnIslemTurChanging(value);
					this.SendPropertyChanging();
					this._IslemTur = value;
					this.SendPropertyChanged("IslemTur");
					this.OnIslemTurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvrakNo", DbType="VarChar(16) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string EvrakNo
		{
			get
			{
				return this._EvrakNo;
			}
			set
			{
				if ((this._EvrakNo != value))
				{
					this.OnEvrakNoChanging(value);
					this.SendPropertyChanging();
					this._EvrakNo = value;
					this.SendPropertyChanged("EvrakNo");
					this.OnEvrakNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MalKodu", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string MalKodu
		{
			get
			{
				return this._MalKodu;
			}
			set
			{
				if ((this._MalKodu != value))
				{
					this.OnMalKoduChanging(value);
					this.SendPropertyChanging();
					this._MalKodu = value;
					this.SendPropertyChanged("MalKodu");
					this.OnMalKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Miktar", DbType="Decimal(25,6) NOT NULL")]
		public decimal Miktar
		{
			get
			{
				return this._Miktar;
			}
			set
			{
				if ((this._Miktar != value))
				{
					this.OnMiktarChanging(value);
					this.SendPropertyChanging();
					this._Miktar = value;
					this.SendPropertyChanged("Miktar");
					this.OnMiktarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fiyat", DbType="Decimal(25,6) NOT NULL")]
		public decimal Fiyat
		{
			get
			{
				return this._Fiyat;
			}
			set
			{
				if ((this._Fiyat != value))
				{
					this.OnFiyatChanging(value);
					this.SendPropertyChanging();
					this._Fiyat = value;
					this.SendPropertyChanged("Fiyat");
					this.OnFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tutar", DbType="Decimal(25,6) NOT NULL")]
		public decimal Tutar
		{
			get
			{
				return this._Tutar;
			}
			set
			{
				if ((this._Tutar != value))
				{
					this.OnTutarChanging(value);
					this.SendPropertyChanging();
					this._Tutar = value;
					this.SendPropertyChanged("Tutar");
					this.OnTutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Birim", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string Birim
		{
			get
			{
				return this._Birim;
			}
			set
			{
				if ((this._Birim != value))
				{
					this.OnBirimChanging(value);
					this.SendPropertyChanging();
					this._Birim = value;
					this.SendPropertyChanged("Birim");
					this.OnBirimChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STK")]
	public partial class STK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _MalKodu;
		
		private string _MalAdi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMalKoduChanging(string value);
    partial void OnMalKoduChanged();
    partial void OnMalAdiChanging(string value);
    partial void OnMalAdiChanged();
    #endregion
		
		public STK()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MalKodu", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MalKodu
		{
			get
			{
				return this._MalKodu;
			}
			set
			{
				if ((this._MalKodu != value))
				{
					this.OnMalKoduChanging(value);
					this.SendPropertyChanging();
					this._MalKodu = value;
					this.SendPropertyChanged("MalKodu");
					this.OnMalKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MalAdi", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MalAdi
		{
			get
			{
				return this._MalAdi;
			}
			set
			{
				if ((this._MalAdi != value))
				{
					this.OnMalAdiChanging(value);
					this.SendPropertyChanging();
					this._MalAdi = value;
					this.SendPropertyChanged("MalAdi");
					this.OnMalAdiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_veridoldurResult
	{
		
		private short _IslemTur;
		
		private string _EvrakNo;
		
		private System.Nullable<System.DateTime> _Tarih;
		
		private decimal _GirisMiktar;
		
		private decimal _CikisMiktar;
		
		public sp_veridoldurResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IslemTur", DbType="SmallInt NOT NULL")]
		public short IslemTur
		{
			get
			{
				return this._IslemTur;
			}
			set
			{
				if ((this._IslemTur != value))
				{
					this._IslemTur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvrakNo", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string EvrakNo
		{
			get
			{
				return this._EvrakNo;
			}
			set
			{
				if ((this._EvrakNo != value))
				{
					this._EvrakNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this._Tarih = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GirisMiktar", DbType="Decimal(25,6) NOT NULL")]
		public decimal GirisMiktar
		{
			get
			{
				return this._GirisMiktar;
			}
			set
			{
				if ((this._GirisMiktar != value))
				{
					this._GirisMiktar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CikisMiktar", DbType="Decimal(25,6) NOT NULL")]
		public decimal CikisMiktar
		{
			get
			{
				return this._CikisMiktar;
			}
			set
			{
				if ((this._CikisMiktar != value))
				{
					this._CikisMiktar = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
